#!/bin/bash
set -euo pipefail

resource_group=""
runtime=""
price_tier=""

usage_example="Usage: $0 -g <resource_group> -r <runtime> -t <price_tier>"

# Named parameter setup
while getopts "g:r:t:" opt; do
  case $opt in
    g) resource_group="${OPTARG}" ;;
    r) runtime="${OPTARG}" ;;
    t) price_tier="${OPTARG}" ;;
    \?)
      echo "${usage_example}"
      exit 1
      ;;
  esac
done

shift $((OPTIND - 1))

# Verify all required parameters are present
if [[ -z "$resource_group" || -z "$runtime" || -z "$price_tier" ]]; then
  echo "Error: Required parameters are missing." >&2
  echo "$usage_example"
  exit 1
fi

echo -e "Will deploy resources using supplied values:\n\tResource group: ${resource_group}\n\tRuntime: ${runtime}\n\tPrice Tier: ${price_tier}"

sleep 5

working_dir=${PWD}
script_dir=$(dirname "$(realpath ${0})")
wan_ip=$(curl ip.me)

source ${script_dir}/webapp-deploy
source ${script_dir}/sqlsrv-deploy
source ${script_dir}/keyvault-deploy
source ${script_dir}/monitoring-deploy
source ${script_dir}/storage-deploy

repo_owner=$(gh api user -q .login)
project_name="$(basename ${working_dir})"
plan_name="${project_name}-asp"
app_name="${project_name}-app"
app_id=""
app_object_id=""
app_principal_id=""
sub_id=""
tenant_id=""
db_name="${project_name}-db"
db_srv="${db_name}-srv"
db_connstring=""
db_connstring_secret=""
keyvault_name="${project_name}-${RANDOM}"
keyvault_id=""
keyvault_uri=""
repo_path="${repo_owner}/${project_name}"

# Webapp orchestration
echo -e "\n>>> Creating App Service Plan..."
app_plan_create

echo -e "\n>>> Creating Web App..."
webapp_create
webapp_set_ip_restrictions

# SQL Server orchestration
echo -e "\n>>> Creating SQL Server..."
sqlsrv_create

echo -e "\n>>> Creating SQL Server Database..."
sqldb_create

echo -e "\n>>> Whitelisting Possible Web App IP Addresses in SQL Server Firewall..."
sqlsrv_whitelist_appsvc_ips

## Keyvault orchestration
echo -e "\n>>> Creating Key Vault..."
keyvault_create

if [ -z $keyvault_id ]; then
  echo "ERROR: Key Vault ID is empty. The vault failed to create (possibly naming conflict)."
  exit 1
fi

echo -e "\n>>> Assigning admin permissions to Key Vault for current user..."
keyvault_assign_admin_permissions

echo -e "\n>>> Assigning permissions to Key Vault for Web App..."
keyvault_assign_appsvc_permissions

echo -e "\n>>> Creating SQL Database Connection String secret..."
keyvault_set_connstring_secret

echo -e "\n>>> Configuring environment variable with Secret URI in Web App..."
webapp_set_connstring

echo -e "\n>>> Configuring Web App monitoring before deployment..."
monitoring_create_law
monitoring_create_appinsights
monitoring_store_secret
webapp_configure_monitoring

echo -e "\n>>> Configuring Storage and Daily Backups..."
storage_create
storage_create_container
storage_mount_file_share
webapp_configure_storage_mount
webapp_configure_backup
webapp_configure_storage_logs

echo -e "\n>>> Configuring GitHub Actions CI/CD for Web App..."
webapp_deploy
