#!/bin/bash

keyvault_create() {
  existing_keyvault_name=$(az keyvault list \
    --resource-group "$resource_group" \
    --query "[?starts_with(name, '${project_name}-')].name | [0]" \
    --output tsv 2>/dev/null || true)

  if [ -n "$existing_keyvault_name" ]; then
    echo -e "\tKey vault already exists (${existing_keyvault_name}), skipping creation..."

    keyvault_name="$existing_keyvault_name"

    keyvault_id=$(az keyvault show \
      --resource-group "$resource_group" \
      --name "$keyvault_name" \
      --query id \
      --output tsv 2>/dev/null || true)
  else
    keyvault_id=$(az keyvault create \
      --location swedencentral \
      --name "$keyvault_name" \
      --resource-group "$resource_group" \
      --enable-rbac-authorization true \
      --query id \
      --output tsv)
    echo -e "\tKey Vault ${keyvault_name} was created."
  fi
}

keyvault_assign_admin_permissions() {
  role="Key Vault Secrets Officer"
  user_oid=$(az ad signed-in-user show \
    --query id \
    --output tsv 2>/dev/null || true)

  assignment_exists=$(az role assignment list \
    --assignee "$user_oid" \
    --role "$role" \
    --scope "$keyvault_id" \
    --query "[0].id" \
    --output tsv 2>/dev/null || true)

  if [ -z "$assignment_exists" ]; then
    az role assignment create \
      --role "$role" \
      --assignee-object-id "$user_oid" \
      --assignee-principal-type User \
      --scope "$keyvault_id"

    echo -e "\tWaiting 45 seconds for Azure RBAC to propagate..."
    sleep 45
  else
    echo -e "\tCurrent user has already been assigned $role, skipping assignment creation"
  fi
}

keyvault_assign_appsvc_permissions() {
  role="Key Vault Secrets User"
  assignment_exists=$(az role assignment list \
    --assignee "$app_principal_id" \
    --role "$role" \
    --scope "$keyvault_id" \
    --query "[0].id" \
    --output tsv 2>/dev/null || true)

  if [ -z "$assignment_exists" ]; then
    az role assignment create \
      --role "$role" \
      --assignee-object-id "$app_principal_id" \
      --assignee-principal-type ServicePrincipal \
      --scope "$keyvault_id"
  else
    echo -e "\tKey Vault Role Assignment already exists, skipping creation"
  fi
}

keyvault_set_connstring_secret() {

  secret_name="${db_name}-connstring"
  db_connstring_secret=$(az keyvault secret show \
    --name "$secret_name" \
    --vault-name "$keyvault_name" \
    --query id \
    --output tsv 2>/dev/null || true)

  if [ -z "$db_connstring_secret" ]; then
  db_connstring="Server=tcp:${db_srv}.database.windows.net,1433;Initial Catalog=${db_name};User ID=${repo_owner};Password=${db_password};Trusted_Connection=False;Encrypt=True"
  db_connstring_secret=$(az keyvault secret set \
      --name "${db_name}-connstring" \
      --vault-name "$keyvault_name" \
      --value "$db_connstring" \
      --description "Database Connection String for ${db_name}" \
      --disabled false \
      --query id \
      --output tsv)
    else
      echo -e "\tKey Vault Secret already exists, skipping creation"
  fi
}
