#!/bin/bash


dirname=$(basename $PWD)
repo_name=${dirname}
description=${4:-"$repo_name"}

github_cli_installed() {
  if type -P pacman >/dev/null 2>&1; then
    pacman -Qi github-cli >/dev/null 2>&1
    return $?
  elif type -P dpkg >/dev/null 2>&1; then
    dpkg -s gh >/dev/null 2>&1
    return $?
  elif type -P rpm >/dev/null 2>&1; then
    rpm -q gh >/dev/null 2>&1
    return $?
  elif type -P apk >/dev/null 2>&1; then
    apk info -e github-cli >/dev/null
    return $?
  elif type -P brew >/dev/null 2>&1; then
    brew list gh >/dev/null 2>&1
    return $?
  else
    return 1
  fi
}

if github_cli_installed; then
  printf "repo: |%s|\ndir:  |%s|\n" "$repo_name" "$dirname" | cat -A
  if [ ${repo_name} != ${dirname} ]; then
    repo_path="$PWD/${repo_name}"
    mkdir -p "${repo_path}"
    cd "${repo_path}"
  else
     repo_path="$PWD"
  fi

  # Check if in repository and if not initialise one with main branch and README.md
  if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git init
  fi
  git branch -M main
  
  if [ ! -f README.md ]; then
    echo "# ${repo_name} - ${description}" > README.md
  fi
  
  git add .
  git commit -m "Script commit" || true

  github_username=$(gh api user --jq .login)

  if [[ -z "${github_username}" ]]; then
    echo -e "\tError retrieving logged in username, make sure GitHub CLI is authenticated properly before continuing"
    exit 1
  fi

  if ! gh repo view "${github_username}/${repo_name}" >/dev/null 2>&1; then
    gh repo create "${repo_name}" \
      --public \
      --description "${description}" \
      --source=${repo_path} \
      --remote=origin \
      --push
  else
    echo -e "\tGitHub repository ${github_username}/${repo_name} already exists, skipping creation"
    git push origin main
  fi

  echo -e "\tLocal repo created at ${repo_path} and pushed to GitHub at https://github.com/$(gh api user --jq .login)/${repo_name}.git"
else 
  echo -e "\tPlease install github-cli before use"
  exit 1
fi
