#!/bin/bash

az config set extension.use_dynamic_install=yes_without_prompt >/dev/null 2>&1

monitoring_create_law() {
  workspace_name="${project_name}-law"

  echo -e "\nChecking Log Analytics Workspace..."

  if ! az monitor log-analytics workspace show \
    --resource-group "$resource_group" \
    --workspace-name "$workspace_name" >/dev/null 2>&1
  then
    echo -e "\tCreating Log Analytics Workspace..."
    workspace_id=$(az monitor log-analytics workspace create \
      --resource-group "$resource_group" \
      --workspace-name "$workspace_name" \
      --query id \
      --output tsv)
  else
    echo -e "\tLog Analytics Workspace already exists, skipping creation..."
  fi

  workspace_id=$(az monitor log-analytics workspace show \
    --resource-group "$resource_group" \
    --workspace-name "$workspace_name" \
    --query id \
    --output tsv)
}

monitoring_create_appinsights() {
  ai_name="${project_name}-ai"

  echo -e "\nChecking Application Insights..."
  if ! az monitor app-insights component show \
    --resource-group "$resource_group" \
    --app "$ai_name" >/dev/null 2>&1
  then
    echo "Creating Application Insights..."
    az monitor app-insights component create \
      --resource-group "$resource_group" \
      --app "$ai_name" \
      --location swedencentral \
      --workspace "$workspace_id" \
      --kind web \
      --application-type web >/dev/null 
  else
    echo "Application Insights already exists, skipping creation..."
  fi
}

monitoring_store_secret() {
  ai_secret_name="${ai_name}-connstring"
  ai_connection_string=$(az monitor app-insights component show \
    --resource-group "$resource_group" \
    --app "$ai_name" \
    --query connectionString \
    --output tsv)

  echo -e "\nChecking if Application Insights connection string is in Key Vault..."
  if ! az keyvault secret show \
    --vault-name "$keyvault_name" \
    --name "$ai_secret_name" >/dev/null 2>&1
  then
    echo -e "\tSaving connection string to Key Vault..."
    az keyvault secret set \
      --vault-name "$keyvault_name" \
      --name "$ai_secret_name" \
      --value "$ai_connection_string" \
      --description "Application Insights Connection String for ${ai_name}" >/dev/null
  else
    echo -e "\tSecret already exists in Key Vault, skipping creation..."
  fi
}
