#!/bin/bash

app_plan_create() {
  az appservice plan create \
    --resource-group $resource_group \
    --name $plan_name \
    --sku $price_tier
}

webapp_create() {
  az webapp create \
    --resource-group $resource_group \
    --plan-name $plan_name \
    --name $app_name \
    --runtime $runtime
}

webapp_auth_gh() {
  app_id=$(az ad app create \
    --display-name $app_name \
    --query appId \
    --output tsv)

  app_object_id=$(az ad sp create \
    --id $app_id \
    --query id \
    --output tsv)

  sub_id=$(az account show \
    --query id \
    --output tsv)

  az role assignment create \
    --role "Website Contributor" \
    --subscription $sub_id
    --assignee-object-id $app_object_id
    --assignee-principal-type ServicePrincipal \
    --scope /subscriptions/$sub_id/resourceGroups/$resource_group/providers/Microsoft.Web/sites/$app_name

    cat<<EOF > credential.json
    {
      "name": "github-actions-credential",
      "issuer": "https://token.actions.githubusercontent.com",
      "subject": "repo:${repo_path}:ref:refs/heads/main",
      "description": "GitHub Actions OIDC Trust",
      "audiences": [
        "api://AzureADTokenExchange"
      ]
    }
EOF

  az ad app federated-credential create \
    --id $app_id
    --parameters credential.json
}

webapp_deploy() {

  // Only if not called from a pre-existing git repository
  if ! $(git rev-parse --is-inside-work-tree 2>/dev/null);then
    // Initialize git repo then creates and pushes it to GitHub with their CLI
    mkghrepo
  fi

  webapp_auth_gh
  tenant_id=$(az account show \
    --query tenantId \
    --output tsv)

  gh secret set AZURE_CLIENT_ID \
    --body "$app_id" \
    --repo ${repo_path}

  gh secret set AZURE_TENANT_ID \
    --body "$tenant_id" \
    --repo ${repo_path}

  gh secret set AZURE_SUBSCRIPTION_ID \
    --body "$sub_id"

  mkdir -p .github/workflows
  cat<<EOF > .github/workflows/az-workflow.yml
  name: Build and Deploy .NET 10 App via OIDC

  on:
    push:
      branches:
        - main
    workflow_dispatch:

  permissions:
    id-token: write
    contents: read

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Azure Login via OIDC
          uses: azure/login@v2
          with:
            client-id: \${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: \${{ secrets.AZURE_TENANT_ID }}
            subscription: \${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Setup .NET 10
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '10.0.x'

        - name: Build with .NET CLI
          working-directory: ./${project_name}-api
          run: dotnet build --configuration Release

        - name: Publish with .NET CLI
          working-directory: ./${project_name}-api
          run: dotnet publish -c Release -o ../../publish

        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v3
          with:
            app-name: '${project_name}'
            package: ./publish
EOF

}

